import { Tooltip } from 'react-tooltip';

type Props = {
  data: CompanyOverview;
};

const CompanyStatement = ({ data }: Props) => {
  return (
    <>
      <h3 className="font-medium text-2xl mb-4">Financial Statements</h3>
      <div className="grid grid-cols-2 gap-x-4">
        <div className="mb-4">
          <p className="mb-2">
            <span
              className="font-bold text-gray-800"
              data-tooltip-id="revenue-ttm-tooltip"
              data-tooltip-content="The total revenue generated by the company over the trailing twelve months."
              data-tooltip-place="top-start"
            >
              Revenue (TTM):
            </span>{' '}
            {data.RevenueTTM} {data.Currency}
          </p>
          <p className="mb-2">
            <span
              className="font-bold text-gray-800"
              data-tooltip-id="gross-profit-ttm-tooltip"
              data-tooltip-content="The total revenue minus the cost of goods sold over the trailing twelve months."
              data-tooltip-place="top-start"
            >
              Gross Profit (TTM):
            </span>{' '}
            {data.GrossProfitTTM} {data.Currency}
          </p>
          <p className="mb-2">
            <span
              className="font-bold text-gray-800"
              data-tooltip-id="diluted-eps-ttm-tooltip"
              data-tooltip-content="The company's earnings per share (EPS) calculated using diluted shares outstanding over the trailing twelve months."
              data-tooltip-place="top-start"
            >
              Diluted EPS (TTM):
            </span>{' '}
            {data.DilutedEPSTTM} {data.Currency}
          </p>
        </div>
        <div className="mb-4">
          <p className="mb-2">
            <span
              className="font-bold text-gray-800"
              data-tooltip-id="quarterly-earnings-growth-tooltip"
              data-tooltip-content="The percentage change in earnings compared to the same quarter in the previous year."
              data-tooltip-place="top-start"
            >
              Quarterly Earnings Growth (YoY):
            </span>{' '}
            {data.QuarterlyEarningsGrowthYOY}%
          </p>
          <p className="mb-2">
            <span
              className="font-bold text-gray-800"
              data-tooltip-id="quarterly-revenue-growth-tooltip"
              data-tooltip-content="The percentage change in revenue compared to the same quarter in the previous year."
              data-tooltip-place="top-start"
            >
              Quarterly Revenue Growth (YoY):
            </span>{' '}
            {data.QuarterlyRevenueGrowthYOY}%
          </p>
        </div>
      </div>

      <Tooltip id="revenue-ttm-tooltip" />
      <Tooltip id="gross-profit-ttm-tooltip" />
      <Tooltip id="diluted-eps-ttm-tooltip" />
      <Tooltip id="quarterly-earnings-growth-tooltip" />
      <Tooltip id="quarterly-revenue-growth-tooltip" />
    </>
  );
};

export default CompanyStatement;
